### ISSUE TITLE
Figure out Input Groups

### ISSUE THREAD

**Issue by jpeterson** [Esri/calcite-react#18]
Link to Calcite Web: http://esri.github.io/calcite-web/documentation/components/#input-groups

Decide how we want to implement input Calcite groups.

**Comment by gavinr** [comment]
What was the resolution for `input-group`?

**Comment by codylawson** [comment]
@gavinr We're doing this with "adornments". https://calcite-react.netlify.com/text-field#advanced-usage

Does that work for your case?

**Comment by gavinr** [comment]
Works for me. Thanks!
