### ISSUE TITLE
MenuItem or ListItem should be able to support `disabled` state

### ISSUE THREAD

**Issue by sethisameer** [Esri/calcite-react#240]
MenuItem or ListItem should be able to support `disabled` state.

In some use cases its required that UI render the menu item but in `disabled` state if it does not meets certain logical conditions. At present only workaround is to add custom style with opacity adjustment along with conditional handling of the onClick handler. 
Desired behavior should be to expose a `disabled` property from within the MenutItem/ListItem components.

**Comment by codylawson** [comment]
Thanks for adding this issue @sethisameer, it definitely slipped through the cracks
