### ISSUE TITLE
Add light dropdown-menu for Navigation 

### ISSUE THREAD

**Issue by SaschaBrunnerCH** [Esri/calcite-react#250]
I could not find a way to add a light dropdown in the navigation like this:
http://esri.github.io/calcite-web/documentation/components/#dropdowns

or like in AGOL:
https://zrhdata.mapsqa.arcgis.com/home/webmap/viewer.html?useExisting=1

![image](https://user-images.githubusercontent.com/46531184/57192663-41d4ef80-6f33-11e9-81d7-b250bdd54c4a.png)

Is there a way to do it with this version?

**Comment by codylawson** [comment]
Hey @SaschaBrunnerCH, currently dropdowns are "roll your own". We've talked about making an uncontrolled dropdown component with a simplified implementation, but right now the closest thing would be the [`Popover`](https://calcite-react.netlify.com/popover). The `targetEl` property can be modified to display a button similar to what your screenshot shows.

Here's an example of what that might look like:
```
targetEl={
  <Button
    transparent
    icon={<ChevronDownIcon />}
    onClick={this.togglePopover}
  />
}
```

Let me know if this doesn't meet your requirements or you need more details.

**Comment by SaschaBrunnerCH** [comment]
@codylawson Thanks for pointing me to the right direction. This works for me:
https://gist.github.com/SaschaBrunnerCH/b25185b6a53224e6b584a1ddbe36a148
