### ISSUE TITLE
Menu/MenuItem should support size options small, extraSmall like Buttons

### ISSUE THREAD

**Issue by sethisameer** [Esri/calcite-react#251]
The Menu/MenuItem could be potentially used for contextual menu. The contextual menu items need not be same size are regular menus. It would be great if the Menu/MenuItem components could inherit the size properties of Button component. Like small, extraSmall and so on...

Also, for consideration to have some color options for border or complete color options as of Buttons.

**Comment by jgibson02** [comment]
The size props for Menu are currently booleans for each size option, should we continue with this pattern or have a `size` prop with values such as `extraSmall`, `small`, etc?

**Comment by codylawson** [comment]
@jgibson02 That may be a good approach. Currently the `Button` component has a similar issue where size and color variants are individual properties. I like how easy it is to use, but it allows for some problems where two properties would conflict with each other.

We should think about this holistically as it should be the same for all components, and would be a breaking change if we decide to go forward with a `size`, `variant` prop with constants as values. I can see benefits to both paths, maybe we can find some more examples and put together a list of props that could be consolidated?

**Comment by jgibson02** [comment]
@sethisameer do you have some examples of what the different desired sizings might look like?

**Comment by sethisameer** [comment]
@jgibson02 -  Only reference, that I've right now is the online version of calcite-react
https://calcite-react.netlify.com/button
This one has the sizes that are currently available.
