### ISSUE TITLE
TypeScript declaration file

### ISSUE THREAD

**Issue by gavinr** [Esri/calcite-react#253]
When trying to use with an app generated by `create-react-app` with the `--typescript` option, you get this error:

```
Could not find a declaration file for module 'calcite-react/CalciteThemeProvider'. 'c:/.........../node_modules/calcite-react/CalciteThemeProvider/index.js' implicitly has an 'any' type.
  Try `npm install @types/calcite-react` if it exists or add a new declaration (.d.ts) file containing `declare module 'calcite-react/CalciteThemeProvider';`ts(7016)
```

## Replication steps: 

1. `npx create-react-app my-app --typescript`
2. `npm i calcite-react`
3. Install in index.tsx per instructions on https://github.com/Esri/calcite-react#usage

**Comment by travisbutcher** [comment]
There is currently no TypeScript file for this.  You can add a typings file to the types for
declare module 'calcite-react/*' 
![image](https://user-images.githubusercontent.com/1291442/57535954-0f8f0d80-72f8-11e9-997d-b32417aca7af.png)

this will allow it to work

**Comment by gavinr** [comment]
Thanks @travisbutcher. Just to clarify the workaround:

1. `npx create-react-app my-app --typescript`
2. Create new folder/file: `src/types/calcite-react/index.d.ts` (this file could be anywhere within `/src`)
3. Contents of `index.d.ts`:
    `declare module 'calcite-react/*';`
4. The typescript compiler should now work without complaints.

Closing as a valid workaround (although if someone in the future wants to create a proper declaration file, I'm sure PRs are accepted :)

**Comment by codylawson** [comment]
@gavinr would it be possible to include this within the calcite-react src itself, until we can get the "proper declaration file"? It would be nice to reduce barriers to entry for common use cases like typescript projects.

Alternatively we may want to include this workaround in our readme as a "gotcha" for typescript projects.

**Comment by travisbutcher** [comment]
on this what is the relation to work here and the work on Calicite Components (https://github.com/ArcGIS/calcite-components).  It is being built from the ground up with Typescript
