### ISSUE TITLE
Slider Component - slider-thumb styling issue in Mozilla

### ISSUE THREAD

**Issue by ChandanMahapatra** [Esri/calcite-react#277]
## Expected Behavior

The slider thumb should be "circle-shaped" in all the browsers
![Screen Shot 2019-07-29 at 15 15 18](https://user-images.githubusercontent.com/14539609/62087450-8f9d8300-b216-11e9-9ae2-01df34ce107d.png)

## Current Behavior

The slider thumb is "square-shaped" in Mozilla Firefox 
![Screen Shot 2019-07-29 at 15 15 05](https://user-images.githubusercontent.com/14539609/62087409-77c5ff00-b216-11e9-9fd5-9c73900cb95c.png)

## Your Environment
* Version used: 0.39.0
* Browser Name and version: Mozilla Firefox Developer Edition - 69.0b8
* Operating System and version (desktop or mobile): MacOS High Sierra - 10.13.6

**Comment by codylawson** [comment]
Resolved in #278
