### ISSUE TITLE
Select: Unnecessary scrollbar in Firefox

### ISSUE THREAD

**Issue by ReneU** [Esri/calcite-react#376]
## Expected Behavior

When using the `Select` component, items that have a bigger width than the defined min-width should not produce a horizontal scroll bar but increase the width of the menu.

## Current Behavior

In Firefox, a horizontal scroll bar is shown for long menu items if we also have a vertical scroll bar (i.e. many items). I guess this happens because in Firefox the vertical scrollbar is not part of the width calculation and thus subtracted from the available width.

## Possible Solution

Not a solution, but what I tried so far: I tried to add something like `min-width: calc(100% + 20px)` but this would limit the menu width to the width of the select element. In other words, if a short item is selected the menu would never be bigger than this even if some options have longer labels.

## Steps to Reproduce (for bugs)

```js
<Playground style={{ height: '250px' }}>
  <Select onChange={value => console.log(value)}>
    <MenuItem value={10}>Menu item with a very long label causes scroll bar</MenuItem>
    <MenuItem value={20}>Twenty</MenuItem>
    <MenuItem value={30}>Thirty</MenuItem>
    <MenuItem value={40}>Forty</MenuItem>
    <MenuItem value={50}>Fifty</MenuItem>
    <MenuItem value={60}>Sixty</MenuItem>
    <MenuItem value={70}>Seventy</MenuItem>
    <MenuItem value={80}>Eighty</MenuItem>
  </Select>
</Playground>
```
## Context + Screenshots

My estimate is that we're talking about ~20px for macOS and ~25px for Windows.

![image](https://user-images.githubusercontent.com/5748802/80489135-ae74a580-895f-11ea-83dd-52765caa5547.png)

## Your Environment

* Version used: Latest
* Browser Name and version: Firefox 75
* Operating System and version (desktop or mobile): macOS + Windows
* Link to your project:

**Comment by codylawson** [comment]
@ReneU Seems related to this long standing bug in Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=764076 . What do you think? Adding specific padding based on the OS is pretty janky, I'll continue to research this to see if there's a more sustainable solution.

**Comment by ReneU** [comment]
I agree. All solutions I found so far would change the look for other browser.
