### ISSUE TITLE
Cannot read property 'white' of undefined - CHECKBOX COMPONENT

### ISSUE THREAD

**Issue by willnix86** [Esri/calcite-react#379]
When trying to use the Checkbox component, my app crashes with the above error. It doesn't matter how many or how few of the APIs props I use, adding Checkbox to the app breaks it.

## Expected Behavior
I should be able to import the Checkbox component and see it displayed in the app, without the app crashing.

## Current Behavior
The app crashes unless I comment out the Checkbox components.
```
The above error occurred in the <StyledDisplayCheckbox> component:
    in StyledDisplayCheckbox (created by Checkbox)
    in label (created by StyledCheckboxGroup)
    in StyledCheckboxGroup (created by Checkbox)
    in Checkbox (at timeline.tsx:85)
    in div (at timeline.tsx:84)
```

## Possible Solution
It looks as though the issue is coming from the 'Checkbox-styled.js' file. On line 38 where various functions are working through 'props.theme.palette...'.

Adding the following to each place where props.theme.palette is read enables the app to run:

if (!props.theme.palette) { return; }

but this seems to stop the app from rendering it's checked state styles (I think - hard to say as the Checkbox doesn't work as it normally should without the above change.

## Steps to Reproduce (for bugs)
1. Create an app
2. Import Checkbox
3. Add Checkbox to component
4. Run app

## Context + Screenshots
I am building out a TypeScript app for a client. I have a component that needs to include checkboxes, as soon as I add the checkbox components, the app crashes.

The only other change I'd made before encountering this was to add a 'calcite-react' types folder to my project with the following inside an index.d.ts file.

```
// SILENCES TYPESCRIPT LINT ERROR FOR USING CALCITE REACT
declare module 'calcite-react/*';
```

## Your Environment
* Version used: 0.51.1
* Browser Name and version: Chrome  81.0.4044.122
* Operating System and version (desktop or mobile): Desktop Mac Catalina 10.15.4
* Link to your project: N/A

**Comment by jpeterson** [comment]
@willnix86 Thanks for the descriptive issue 🙂 

My guess is that you are not wrapping your app in a theme provider.

Check out the [Theme Provider](https://calcite-react.netlify.app/#theme-provider) section in the docs.

```jsx
import React from 'react';
import ReactDOM from 'react-dom';

import CalciteThemeProvider from 'calcite-react/CalciteThemeProvider';

import App from 'path/to/App';

ReactDOM.render(
  <CalciteThemeProvider>
    <App />
  </CalciteThemeProvider>,
  document.getElementById('root')
);
```
