### ISSUE TITLE
ArcgisAccount - useAccountManager addAccount() returning 500 error when used with Enterprise

### ISSUE THREAD

**Issue by alexanderela** [Esri/calcite-react#399]
## Expected Behavior
The expected behavior upon invoking the returned `addAccount` function should be to prompt the user to login to ArcGIS.

## Current Behavior
Invoking the returned `addAccount` function after passing the following options object to the `useAccountManager()` hook results in a 500 error.  The following options are from an ArcGIS Enterprise account.

```
const options = {
    clientId: "1d9YbkgzIAdAPviU",
    redirectUri: `${window.location.origin}`,
    popup: false,
    portalUrl: "https://ps0008452.esri.com/portal",
  };
```

## Steps to Reproduce (for bugs)
1.  Pass the above options object to the `useAccountManager` hook:
```
  const { accountManagerState, addAccount, removeAccount } = useAccountManager({
    options,
  });
```
2. Invoke the returned `addAccount` function.
3.  See the console and network tabs for 500 error.

## Context + Screenshots
![Screen Shot 2020-08-19 at 4 05 00 PM](https://user-images.githubusercontent.com/30238776/90695313-6d1e4380-e237-11ea-8c01-91a2532c0da7.png)
![Screen Shot 2020-08-19 at 4 05 12 PM](https://user-images.githubusercontent.com/30238776/90695323-6f809d80-e237-11ea-9832-11509da1b0bc.png)
![Screen Shot 2020-08-19 at 4 05 26 PM](https://user-images.githubusercontent.com/30238776/90695325-70b1ca80-e237-11ea-93cf-5c164aa5d82e.png)

**Comment by brandonlammey** [comment]
Task #418 will resolve documentation of appropriate url format as well as enhancement for checking urls
