### ISSUE TITLE
Tooltip in minimal TextField rightAdornment shows right and bottom borders

### ISSUE THREAD

**Issue by samMatenaer** [Esri/calcite-react#430]
![image](https://user-images.githubusercontent.com/50883428/99104761-09da4e00-25a7-11eb-80b5-56449a2f24f0.png)

Any component in a rightAdornment, wrapped with a tooltip renders borders on the bottom and right hand side. This happens regardless of the component the tooltip is wrapped around,

Code to reproduce this issue:
```js
<TextField
        minimal
        rightAdornment={
          <Tooltip title="Load Layer">
            <Button>Submit</Button>
          </Tooltip>
        }
/>
```

Happens in chrome and firefox.

**Comment by codylawson** [comment]
@samMatenaer This may be fixable using `rightAdornmentNoWrap` or `leftAdornmentNoWrap` properties on the `TextField`. It should remove any extra styling on the adornments. This is automatically used for certain Calcite React elements but not all are included.

We're currently looking at other solutions that will make this unnecessary but at the very least we'll be documenting those props in a later release. Let me know if this solution doesn't work for you and we can look for other options.

**Comment by samMatenaer** [comment]
@codylawson rightAdornmentNoWrap worked for this, thanks for the help.
