### ISSUE TITLE
Bug: CalciteA color

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-react#461]
### Expected Behavior
CalciteA component should be brand blue

### Current Behavior

When the CalciteA has an href it's the default browser blue

![Screen Shot 2021-03-25 at 9.37.59 AM.png](https://images.zenhubusercontent.com/5ee3dcd2f6e0252a919ce9be/cec603c1-ab4f-4496-b5cc-01388e22a807)

When the CalciteA doesn't have an href it's black

![Screen Shot 2021-03-25 at 9.38.19 AM.png](https://images.zenhubusercontent.com/5ee3dcd2f6e0252a919ce9be/234e5f65-09b1-403e-86d8-6824af2bad6f)

* Browser Name and version: Chrome
* Link to your project: https://pr-217.assistant.aws.esri-ps.com/

**Comment by codylawson** [comment]
This should be resolved by latest calcite react https://github.com/Esri/calcite-react/releases/tag/v0.58.0 when we update the package.
